# Generated by Django 4.0.4 on 2022-04-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputFile', models.FileField(upload_to='input/')),
                ('outputFile', models.FileField(null=True, upload_to='output/')),
            ],
        ),
    ]
